<?php /** @var \Swissup\Core\Block\Adminhtml\Config\Form\Field\VirtualCheck $block */ ?>
<?php /** @var \Magento\Framework\Escaper $escaper */ ?>
<style>
#swissup_core_troubleshooting:has(.swissup-virtualfix-success) .fix-themes-container { display: none }
#swissup_core_troubleshooting .fix-themes-container { margin-top: 20px; }
#swissup_core_troubleshooting .themes-table .swissup-badge::before {
    display:inline-block;
    content: '';
    width: 10px;
    height: 10px;
    background-color: #cc1017;
    border-radius: 50%;
    margin-right: 6px;
    vertical-align: middle;
}
</style>

<?php $themes = $block->getVirtualThemes(); ?>

<?php if (!$themes): ?>
    <p class="swissup-virtualfix-success" style="color: green;">No virtual themes found. Check: passed!</p>
<?php else: ?>
    <table class="swissup-config-table">
        <thead>
            <tr>
                <th scope="col"><?= $escaper->escapeHtml(__('Theme')) ?></th>
                <th scope="col"><?= $escaper->escapeHtml(__('Path')) ?></th>
                <th scope="col"><?= $escaper->escapeHtml(__('Status')) ?></th>
            </tr>
        </thead>
    	<tbody>
            <?php foreach ($themes as $theme): ?>
    		<tr>
                <td><?= $escaper->escapeHtml($theme['title']) ?></td>
                <td class="font-mono"><?= $escaper->escapeHtml($theme['path'] ?: '—') ?></td>
                <td><span class="swissup-badge"><?= $escaper->escapeHtml($theme['status']) ?></span></td>
            </tr>
            <?php endforeach; ?>
    	</tbody>
    </table>
<?php endif; ?>
