<style>
    #row_swissup_core_troubleshooting_virtualcheck .themes-table h4 {padding-left: 0}
    #row_swissup_core_troubleshooting_virtualcheck .themes-table table {max-width: 500px}
	#row_swissup_core_troubleshooting_virtualcheck .themes-table td	{ text-align-last: left; }
	#row_swissup_core_troubleshooting_virtualcheck .themes-table th { text-align-last: left; }

    #row_swissup_core_troubleshooting_virtualcheck .themes-table td.virtual::before { 
        display:inline-block; 
        content: '';
        width: 15px;
        height: 15px;
        background-color: red;
        border-radius: 50%;
        margin-right: 10px;
        vertical-align: middle;
    }
	
</style>



<h4>Virtual Theme Check</h4>

<?php 
if ($block->getVirtualThemes()): ?>
    <p style="color: green;">No virtual themes found. Check: passed!</p>
<?php else: ?>
    <table>
    	<tbody>
            <?php foreach ($block->getVirtualThemes() as $theme): ?>
    		<tr>
                <td scope="row"><?php echo $theme->getThemeTitle(); ?></th>
                <td class="virtual">Virtual</th>
            </tr>
            <?php endforeach; ?>
    	</tbody>
    </table>
<?php endif; ?>
